Test CI (#28)
* Updated upstream_update.yml workflow -> added 'Payload sanity check' job

* Fix typo in update_versions.yaml workflow

* Updated update_versions.yaml workflow -> added computing of commit message

diff --git a/.github/workflows/upstream_update.yml b/.github/workflows/upstream_update.yml
--- a/.github/workflows/upstream_update.yml
+++ b/.github/workflows/upstream_update.yml
@@ -5,21 +5,45 @@ on:
     types: [upstream_update]
 
 jobs:
-  test:
-    name: Integration test
+  check:
+    name: Payload sanity check
     runs-on: ubuntu-latest
     if: ${{ github.event.client_payload.upstream_update || github.event.client_payload.sidecar_update }}
     steps:
-      - name: Check and prepare
+      - name: Payload sanity check
+        run: |
+          if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
+            echo "Upstream update was requested"
+            if [ -z ${{ github.event.client_payload.upstream_tag }} ]; then
+              echo "Upstream tag is empty! It should be set in 'client_payload.upstream_tag' property. \nPayload sanity check failed! Exiting ..."
+              exit 1
+            else
+              echo "OK"
+            fi
+          fi
+      
+          if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
+            echo "Sidecar update was requested"
+            if [ -z ${{ github.event.client_payload.sidecar_tag }} ]; then
+              echo "Sidecar tag is empty! It should be set in 'client_payload.sidecar_tag' property. \nPayload sanity check failed! Exiting ..."
+              exit 1
+            else
+              echo "OK"
+            fi
+          fi
+      
+          echo "Payload sanity check PASSED"
+
+  test:
+    name: Integration test
+    runs-on: ubuntu-latest
+    needs: check
+    steps:
+      - name: Prepare Helm arguments
         run: |
           HELM_ARGS=""
           if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
-            echo "Upstream update was requested"
             UPSTREAM_TAG=${{ github.event.client_payload.upstream_tag }}
-            if [ -z ${UPSTREAM_TAG} ]; then
-              echo "Upstream tag is empty! It should be set in 'client_payload.upstream_tag' property. Exiting ..."
-              exit 1
-            fi
             HELM_ARGS+=" \
             --set postanalytics.addnode.image.tag=${UPSTREAM_TAG} \
             --set postanalytics.exportenv.image.tag=${UPSTREAM_TAG} \
@@ -31,12 +55,7 @@ jobs:
           fi
           
           if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
-            echo "Sidecar update was requested"
             SIDECAR_TAG=${{ github.event.client_payload.sidecar_tag }}
-            if [ -z ${SIDECAR_TAG} ]; then
-              echo "Sidecar tag is empty! It should be set in 'client_payload.sidecar_tag' property. Exiting ..."
-              exit 1
-            fi
             HELM_ARGS+=" --set config.sidecar.image.tag=${SIDECAR_TAG}"
           fi
           
@@ -84,7 +103,6 @@ jobs:
           python -m pip install --upgrade pip
           pip install pytest
           pytest helm/test/integration_test.py
-
 
   update_versions:
     name: Update versions
